# Generated by Django 3.2 on 2023-03-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='emailverification',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payplan',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
