# Generated by Django 3.2 on 2023-03-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20230314_0707'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shortenedurls',
            index=models.Index(fields=['prefix', 'shortend_url'], name='shortener_s_prefix_4b9e16_idx'),
        ),
    ]
