# Generated by Django 4.1.7 on 2023-03-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_users_pay_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
