# Generated by Django 3.2 on 2023-03-16 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20230316_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='custom_params',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='TrackingParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('params', models.CharField(max_length=20)),
                ('shortend_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.shortenedurls')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
