# Generated by Django 3.2 on 2023-03-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20230316_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
