# Generated by Django 3.2 on 2023-03-07 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_shortenerurls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenerurls',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
